const playlistExclude = [
  "\\blive\\b",
  "live\\s*stream",
  "\\blivestream\\b",
  "premiere",
  "\\bevent\\b",
  "special\\s*program",
  "\\bnews\\b",
  "announcement",
  "channel\\s*update",
  "\\bshorts?\\b",
  "\\btrailer(s)?\\b",
  "trailer\\s*only",
  "\\bteaser\\b",
  "\\bpv\\b",
  "\\bpromo\\b",
  "promotional",
  "\\bmusic\\b",
  "\\bsong\\b",
  "\\bop\\b",
  "\\bed\\b",
  "\\bost\\b",
  "opening",
  "ending",
  "karaoke",
  "concert",
  "\\bstage\\b",
  "\\bradio\\b",
  "compilation",
  "highlight",
  "recap",
  "marathon",
  "interview",
  "birthday",
  "behind\\s*the\\s*scene"
];

const videoExclude = [
  "\\blive\\b",
  "live\\s*stream",
  "\\blivestream\\b",
  "\\bevent\\b",
  "special\\s*program",
  "\\bnews\\b",
  "\\bshorts?\\b",
  "\\btrailer\\b",
  "trailer\\s*only",
  "\\bteaser\\b",
  "\\bpv\\b",
  "\\bpromo\\b",
  "\\bmusic\\b",
  "\\bsong\\b",
  "\\bost\\b",
  "opening",
  "ending",
  "karaoke",
  "concert",
  "\\bstage\\b",
  "\\bradio\\b",
  "interview",
  "compilation",
  "recap",
  "announcement",
  "channel\\s*update"
];

export const youtubeImportSources = [
  {
    key: "muse-indonesia",
    name: "Muse Indonesia",
    channelId: "UCxxnxya_32jcKj4yN1_kD7A",
    channelHandle: "@MuseIndonesia",
    sourceChannelUrl: "https://www.youtube.com/channel/UCxxnxya_32jcKj4yN1_kD7A",
    defaultGenres: ["Official YouTube"],
    defaultStatus: "Ongoing",
    playlistInclude: [],
    playlistExclude,
    videoInclude: [],
    videoExclude
  },
  {
    key: "ani-one-indonesia",
    name: "Ani-One Indonesia",
    channelHandle: "@AniOneID",
    sourceChannelUrl: "https://www.youtube.com/@AniOneID",
    defaultGenres: ["Official YouTube"],
    defaultStatus: "Ongoing",
    playlistInclude: [],
    playlistExclude,
    videoInclude: [],
    videoExclude
  }
];
